version: 2

project_name: edge-proxy

before:
  hooks:
    - go test ./...

builds:
  - id: edge-proxy
    main: .
    binary: edge-proxy
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X main.version={{ .Version }} -X main.commit={{ .ShortCommit }} -X main.date={{ .Date }}
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
  - id: edge-backend
    main: ./cmd/backend
    binary: edge-backend
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X main.version={{ .Version }} -X main.commit={{ .ShortCommit }} -X main.date={{ .Date }}
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    formats: [tar.gz]
    format_overrides:
      - goos: windows
        formats: [zip]

checksum:
  name_template: checksums.txt

release:
  github:
    owner: ArkaPrabhaChowdhury
    name: edge-proxy-go
