apiVersion: v1
kind: Service
metadata:
  name: edge-proxy
spec:
  selector:
    app: edge-proxy
  ports:
    - name: proxy
      port: 80
      targetPort: proxy
    - name: stats
      port: 8081
      targetPort: stats
